[server]
port = 8000
enableCORS = false
enableXsrfProtection = false
headless = true
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"

[logger]
level = "info"
